/* Generated By:JJTree: Do not edit this line. DynamicSerDeEnumDef.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeEnumDef extends SimpleNode {
  public DynamicSerDeEnumDef(int id) {
    super(id);
  }

  public DynamicSerDeEnumDef(thrift_grammar p, int id) {
    super(p, id);
  }

}
