/* Generated By:JJTree: Do not edit this line. DynamicSerDeXception.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeXception extends SimpleNode {
  public DynamicSerDeXception(int id) {
    super(id);
  }

  public DynamicSerDeXception(thrift_grammar p, int id) {
    super(p, id);
  }

}
