/* Generated By:JJTree: Do not edit this line. DynamicSerDeSenumDefList.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeSenumDefList extends SimpleNode {
  public DynamicSerDeSenumDefList(int id) {
    super(id);
  }

  public DynamicSerDeSenumDefList(thrift_grammar p, int id) {
    super(p, id);
  }

}
