/* Generated By:JJTree: Do not edit this line. DynamicSerDeConstListContents.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeConstListContents extends SimpleNode {
  public DynamicSerDeConstListContents(int id) {
    super(id);
  }

  public DynamicSerDeConstListContents(thrift_grammar p, int id) {
    super(p, id);
  }

}
