/* Generated By:JJTree: Do not edit this line. DynamicSerDeConstMap.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeConstMap extends SimpleNode {
  public DynamicSerDeConstMap(int id) {
    super(id);
  }

  public DynamicSerDeConstMap(thrift_grammar p, int id) {
    super(p, id);
  }

}
