/* Generated By:JJTree: Do not edit this line. DynamicSerDeEnumDefList.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeEnumDefList extends SimpleNode {
  public DynamicSerDeEnumDefList(int id) {
    super(id);
  }

  public DynamicSerDeEnumDefList(thrift_grammar p, int id) {
    super(p, id);
  }

}
