/* Generated By:JJTree: Do not edit this line. DynamicSerDeInclude.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeInclude extends SimpleNode {
  public DynamicSerDeInclude(int id) {
    super(id);
  }

  public DynamicSerDeInclude(thrift_grammar p, int id) {
    super(p, id);
  }

}
