/* Generated By:JJTree: Do not edit this line. DynamicSerDeUnflagArgs.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeUnflagArgs extends SimpleNode {
  public DynamicSerDeUnflagArgs(int id) {
    super(id);
  }

  public DynamicSerDeUnflagArgs(thrift_grammar p, int id) {
    super(p, id);
  }

}
