/* Generated By:JJTree: Do not edit this line. DynamicSerDeTypeDefinition.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeTypeDefinition extends SimpleNode {
  public DynamicSerDeTypeDefinition(int id) {
    super(id);
  }

  public DynamicSerDeTypeDefinition(thrift_grammar p, int id) {
    super(p, id);
  }

}
