/* Generated By:JJTree: Do not edit this line. DynamicSerDeHeader.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeHeader extends SimpleNode {
  public DynamicSerDeHeader(int id) {
    super(id);
  }

  public DynamicSerDeHeader(thrift_grammar p, int id) {
    super(p, id);
  }

}
