/* Generated By:JJTree: Do not edit this line. DynamicSerDeSenum.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeSenum extends SimpleNode {
  public DynamicSerDeSenum(int id) {
    super(id);
  }

  public DynamicSerDeSenum(thrift_grammar p, int id) {
    super(p, id);
  }

}
