/* Generated By:JJTree: Do not edit this line. DynamicSerDeNamespace.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeNamespace extends SimpleNode {
  public DynamicSerDeNamespace(int id) {
    super(id);
  }

  public DynamicSerDeNamespace(thrift_grammar p, int id) {
    super(p, id);
  }

}
