/* Generated By:JJTree: Do not edit this line. DynamicSerDeConst.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeConst extends SimpleNode {
  public DynamicSerDeConst(int id) {
    super(id);
  }

  public DynamicSerDeConst(thrift_grammar p, int id) {
    super(p, id);
  }

}
