/* Generated By:JJTree: Do not edit this line. DynamicSerDeThrows.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeThrows extends SimpleNode {
  public DynamicSerDeThrows(int id) {
    super(id);
  }

  public DynamicSerDeThrows(thrift_grammar p, int id) {
    super(p, id);
  }

}
