/* Generated By:JJTree: Do not edit this line. DynamicSerDeConstMapContents.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeConstMapContents extends SimpleNode {
  public DynamicSerDeConstMapContents(int id) {
    super(id);
  }

  public DynamicSerDeConstMapContents(thrift_grammar p, int id) {
    super(p, id);
  }

}
