/* Generated By:JJTree: Do not edit this line. DynamicSerDeService.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeService extends SimpleNode {
  public DynamicSerDeService(int id) {
    super(id);
  }

  public DynamicSerDeService(thrift_grammar p, int id) {
    super(p, id);
  }

}
