/* Generated By:JJTree: Do not edit this line. DynamicSerDeConstList.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeConstList extends SimpleNode {
  public DynamicSerDeConstList(int id) {
    super(id);
  }

  public DynamicSerDeConstList(thrift_grammar p, int id) {
    super(p, id);
  }

}
