/* Generated By:JJTree: Do not edit this line. DynamicSerDeFieldValue.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeFieldValue extends SimpleNode {
  public DynamicSerDeFieldValue(int id) {
    super(id);
  }

  public DynamicSerDeFieldValue(thrift_grammar p, int id) {
    super(p, id);
  }

}
