/* Generated By:JJTree: Do not edit this line. DynamicSerDeFlagArgs.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeFlagArgs extends SimpleNode {
  public DynamicSerDeFlagArgs(int id) {
    super(id);
  }

  public DynamicSerDeFlagArgs(thrift_grammar p, int id) {
    super(p, id);
  }

}
