/* Generated By:JJTree: Do not edit this line. DynamicSerDeEnum.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeEnum extends SimpleNode {
  public DynamicSerDeEnum(int id) {
    super(id);
  }

  public DynamicSerDeEnum(thrift_grammar p, int id) {
    super(p, id);
  }

}
