/* Generated By:JJTree: Do not edit this line. DynamicSerDeFunctionType.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeFunctionType extends SimpleNode {
  public DynamicSerDeFunctionType(int id) {
    super(id);
  }

  public DynamicSerDeFunctionType(thrift_grammar p, int id) {
    super(p, id);
  }

}
