/* Generated By:JJTree: Do not edit this line. DynamicSerDeDefinition.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeDefinition extends SimpleNode {
  public DynamicSerDeDefinition(int id) {
    super(id);
  }

  public DynamicSerDeDefinition(thrift_grammar p, int id) {
    super(p, id);
  }

}
