/* Generated By:JJTree: Do not edit this line. DynamicSerDeDefinitionType.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeDefinitionType extends SimpleNode {
  public DynamicSerDeDefinitionType(int id) {
    super(id);
  }

  public DynamicSerDeDefinitionType(thrift_grammar p, int id) {
    super(p, id);
  }

}
