/* Generated By:JJTree: Do not edit this line. DynamicSerDeStart.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeStart extends SimpleNode {
  public DynamicSerDeStart(int id) {
    super(id);
  }

  public DynamicSerDeStart(thrift_grammar p, int id) {
    super(p, id);
  }

}
