/* Generated By:JJTree: Do not edit this line. DynamicSerDeExtends.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeExtends extends SimpleNode {
  public DynamicSerDeExtends(int id) {
    super(id);
  }

  public DynamicSerDeExtends(thrift_grammar p, int id) {
    super(p, id);
  }

}
