/* Generated By:JJTree: Do not edit this line. DynamicSerDeAsync.java */

package com.ebay.nest.io.sede.dynamic_type;

public class DynamicSerDeAsync extends SimpleNode {
  public DynamicSerDeAsync(int id) {
    super(id);
  }

  public DynamicSerDeAsync(thrift_grammar p, int id) {
    super(p, id);
  }

}
